name=GY_MBI160
version=0.0.1
author=IamWerty
maintainer=GYronix <gyronix.official@gmail.com>
sentence=A library written for AirGlove project
paragraph=Small library to work with BMI160 sensor.
category=Sensors
url=https://github.com/IamWerty/BMI160
architectures=*
